name: ngencerf-server

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ../data/db:/var/lib/postgresql/data
    env_file:
      - path: ./postgres_db.env
        required: true
      - path: ./postgres_db.override.env
        required: false
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  ngencerf-services:
    build:
      context: .
      args:
        - MSWM_TAG=${MSWM_TAG}
        - NGEN_FORCING_TAG=${NGEN_FORCING_TAG}
        - CACHE_BUST=${CACHE_BUST}
    image: ghcr.io/ngwpc/ngencerf-server:latest
    pull_policy: build
    ports:
      - "8000:8000"
    volumes:
      - ../data/.ngencerf-init:/ngencerf/ngencerf-server/.init/
      - ${NGEN_CAL_DATA_PATH}:/ngencerf/data/
      - ../logs/ngencerf-server:/ngencerf/ngencerf-server/logs/
    environment:
      - NGEN_CAL_DATA_PATH=${NGEN_CAL_DATA_PATH}
    env_file:
      - path: ./ngencerf_services.env
        required: true
      - path: ./ngencerf_services.override.env
        required: false
    depends_on:
      db:
        condition: service_healthy
        restart: true
