name: ngencerf-server

services:
  ngencerf-services:
    build:
      dockerfile: ./Dockerfile.production-pw
      context: .
      args:
        - MSWM_TAG=${MSWM_TAG}
        - NGEN_FORCING_TAG=${NGEN_FORCING_TAG}
        - CACHE_BUST=${CACHE_BUST}
    image: ghcr.io/ngwpc/ngencerf-server:${NGENCERF_SERVER_TAG:-latest}
    pull_policy: always
    ports:
      - "8000:8000"
    volumes:
      - ../data/.ngencerf-init:/ngencerf/ngencerf-server/.init/
      - ${NGEN_CAL_DATA_PATH}:/ngencerf/data/
      - ../logs/ngencerf-server:/ngencerf/ngencerf-server/logs/
      - ${CONTAINER_PATH}:/ngencerf/containers/
      - /var/run/docker.sock:/var/run/docker.sock
      - /ngencerf-app/aws:/root/.aws:ro
      - /ngencerf-app/django_cache:/var/django_cache
    environment:
      - NGEN_CAL_DATA_PATH=${NGEN_CAL_DATA_PATH}
    env_file:
      - path: ./ngencerf_services.env
        required: true
      - path: ./ngencerf_services.override.env
        required: false
    privileged: true
