# Generated by Django 5.2 on 2025-05-07 20:43

from django.db import migrations


def rename_puerto_rico(apps, schema_editor):
    Domain = apps.get_model("calibration", "Domain")
    Domain.objects.filter(name="Puerto Rico").update(name="Puerto_Rico")


class Migration(migrations.Migration):
    dependencies = [
        ('calibration', '0011_remove_calibrationrun_module_output_variable_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_puerto_rico),
    ]
