# Generated by Django 5.2 on 2025-05-19 18:04

from django.db import migrations


def remove_puerto_rico(apps, schema_editor):
    Domain = apps.get_model("calibration", "Domain")
    Domain.objects.filter(name="Puerto Rico").delete()


class Migration(migrations.Migration):
    dependencies = [
        ('calibration', '0012_rename_puerto_rico'),
    ]

    operations = [
        migrations.RunPython(remove_puerto_rico),
    ]
