# Generated by Django 5.2 on 2025-05-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0013_remove_old_puerto_rico'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='mpi_nprocs',
            field=models.IntegerField(null=True),
        ),
    ]
