# Generated by Django 5.2.2 on 2025-06-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0014_calibrationrun_mpi_nprocs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nwmretrospectivemetrics',
            name='run_type',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='validationmetrics',
            name='run_type',
            field=models.CharField(max_length=25),
        ),
    ]
