# Generated by Django 5.2.2 on 2025-06-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0015_alter_nwmretrospectivemetrics_run_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationformulation',
            name='module_commit_hash',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='ngen_cal_commit_hash',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='ngen_commit_hash',
        ),
        migrations.RemoveField(
            model_name='forecastforcingdownloadrun',
            name='ngen_forcing_commit_hash',
        ),
        migrations.RemoveField(
            model_name='forecastrun',
            name='ngen_commit_hash',
        ),
        migrations.RemoveField(
            model_name='forecastrun',
            name='ngen_forecast_commit_hash',
        ),
        migrations.RemoveField(
            model_name='validationrun',
            name='ngen_cal_commit_hash',
        ),
        migrations.RemoveField(
            model_name='validationrun',
            name='ngen_commit_hash',
        ),
    ]
