# Generated by Django 5.2.2 on 2025-06-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0016_remove_calibrationformulation_module_commit_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotdefinition',
            name='display_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plotdefinition',
            name='lstm_flag',
            field=models.BooleanField(default=False),
        ),
    ]
