# Generated by Django 5.2.2 on 2025-06-25 14:24

from django.db import migrations

def populate_display_name(apps, schema_editor):
    PlotDefinition = apps.get_model('calibration', 'PlotDefinition')
    for obj in PlotDefinition.objects.all():
        obj.display_name = obj.name
        obj.save(update_fields=["display_name"])

class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0017_plotdefinition_display_name_plotdefinition_lstm_flag'),
    ]

    operations = [
        migrations.RunPython(populate_display_name)
    ]
