# Generated by Django 5.2.2 on 2025-06-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0018_populate_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotdefinition',
            name='display_name',
            field=models.CharField(default='dummy', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
