# Generated by Django 5.2.2 on 2025-06-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0019_alter_plotdefinition_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
