# Generated by Django 5.2.5 on 2025-08-13 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0020_calibrationrun_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='forcing_source_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', related_query_name='+', to='calibration.forcingsource'),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='forcing_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', related_query_name='+', to='calibration.forcingsource'),
        ),
    ]
