# Generated by Django 5.2.4 on 2025-08-04 22:28

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0020_calibrationrun_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.status')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_validation',
            },
        ),
        migrations.CreateModel(
            name='DataValidationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=200)),
                ('line_number', models.IntegerField()),
                ('line', models.CharField(max_length=200)),
                ('error', models.CharField(max_length=200)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('data_validation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.datavalidation')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_validation_details',
            },
        ),
        migrations.CreateModel(
            name='VerificationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(null=True)),
                ('run_start', models.DateTimeField(null=True)),
                ('run_end', models.DateTimeField(null=True)),
                ('slurm_job_id', models.IntegerField(null=True)),
                ('verification_yaml_file_path', models.TextField(null=True)),
                ('job_data_dir', models.CharField(max_length=255)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('performance_metrics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.performancemetrics')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.status')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_run',
            },
        ),
    ]
