# Generated by Django 5.2.4 on 2025-08-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0021_datavalidation_datavalidationdetails_verificationrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrun',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
