# Generated by Django 5.2.5 on 2025-08-13 18:22

from django.db import migrations


def rename_obs(apps, schema_editor):
    ObservationalSource = apps.get_model('calibration', 'ObservationalSource')
    ObservationalSource.objects.filter(name="Data Services").update(name='Historical')


def rename_geo(apps, schema_editor):
    GeopackageSource = apps.get_model('calibration', 'GeopackageSource')
    GeopackageSource.objects.filter(name="Data Services").update(name='Hydrofabric')


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0021_calibrationrun_forcing_source_actual_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_obs),
        migrations.RunPython(rename_geo),
    ]
