# Generated by Django 5.2.5 on 2025-08-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0022_rename_obs_and_geopkg_sources'),
        ('calibration', '0022_verificationrun_is_archived'),
    ]

    operations = [
    ]
