# Generated by Django 5.2.5 on 2025-08-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0022_rename_obs_and_geopkg_sources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='forcing_source',
            new_name='forcing_source_requested',
        ),
    ]
