# Generated by Django 5.2.5 on 2025-08-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0023_merge_20250818_1906'),
        ('calibration', '0023_rename_forcing_source_calibrationrun_forcing_source_requested'),
    ]

    operations = [
    ]
