# Generated by Django 5.2.5 on 2025-08-27 22:02

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0023_rename_forcing_source_calibrationrun_forcing_source_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.IntegerField()),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'output_variable',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='output_variables',
            field=models.ManyToManyField(db_table='module_output_variables', to='calibration.outputvariable'),
        ),
    ]
