# Generated by Django 5.2.5 on 2025-08-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0024_merge_20250820_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datavalidationdetails',
            name='data_validation',
        ),
        migrations.RemoveField(
            model_name='datavalidationdetails',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='datavalidationdetails',
            name='updated_by',
        ),
        migrations.AlterModelTable(
            name='verificationrun',
            table='verification_run',
        ),
        migrations.DeleteModel(
            name='DataValidation',
        ),
        migrations.DeleteModel(
            name='DataValidationDetails',
        ),
    ]
