# Generated by Django 5.2.5 on 2025-09-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0024_outputvariable_module_output_variables'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calibrationformulation',
            index=models.Index(fields=['calibration_run'], name='idx_formulation_run'),
        ),
        migrations.AddIndex(
            model_name='calibrationoptimizationinput',
            index=models.Index(fields=['calibration_run', 'optimization_input'], name='idx_optinput_run_input'),
        ),
        migrations.AddIndex(
            model_name='calibrationparameter',
            index=models.Index(fields=['calibration_formulation'], name='idx_parameter_formulation'),
        ),
        migrations.AddIndex(
            model_name='calibrationparameter',
            index=models.Index(fields=['calibration_formulation', 'user_selected_for_tuning'], name='idx_param_formulation_selected'),
        ),
        migrations.AddIndex(
            model_name='calibrationrun',
            index=models.Index(fields=['owner', 'status', 'is_archived'], name='idx_run_owner_status_archived'),
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['calibration_run', 'validation_type'], name='idx_validationrun_run_type'),
        ),
        migrations.AddConstraint(
            model_name='calibrationoptimizationinput',
            constraint=models.UniqueConstraint(fields=('calibration_run', 'optimization_input'), name='uq_optinput_per_run'),
        ),
        migrations.AddConstraint(
            model_name='calibrationstopcriteria',
            constraint=models.UniqueConstraint(fields=('calibration_run',), name='uq_stopcriteria_per_run'),
        ),
    ]
