# Generated by Django 5.2.6 on 2025-09-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0026_calibrationrun_is_aet_rootzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationrun',
            name='user_formulation_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
