# Generated by Django 5.2.5 on 2025-09-10 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0027_alter_calibrationrun_user_formulation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrun',
            name='forecast_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.forecastrun'),
        ),
    ]
