# Generated by Django 5.2.6 on 2025-09-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0027_alter_calibrationrun_user_formulation_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='iteration',
            new_name='idx_iteration_run',
            old_name='iteration_calibration_run_idx',
        ),
        migrations.RenameIndex(
            model_name='iteration',
            new_name='idx_iteration_worker_number',
            old_name='iteration_worker_number_idx',
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='next_worker_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='calibrationrun',
            index=models.Index(fields=['owner', 'is_archived'], name='idx_run_owner_archived'),
        ),
        migrations.AddIndex(
            model_name='iteration',
            index=models.Index(fields=['calibration_run', 'worker_name', '-iteration_num'], name='idx_iter_run_worker_num_desc'),
        ),
    ]
