# Generated by Django 5.2.6 on 2025-09-18 20:49

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0028_rename_iteration_calibration_run_idx_idx_iteration_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastcycle',
            name='availability_lag',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='forecastcycle',
            name='cycle_end',
            field=models.IntegerField(default=23),
        ),
        migrations.AddField(
            model_name='forecastcycle',
            name='cycle_freq',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='forecastcycle',
            name='cycle_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forecastcycle',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='calibration.domain'),
        ),
        migrations.AddField(
            model_name='forecastcycle',
            name='fcst_timestep',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='forecastcycle',
            name='fcst_win',
            field=models.IntegerField(default=48),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='cold_start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='cycle_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='VerificationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(null=True)),
                ('run_start', models.DateTimeField(null=True)),
                ('run_end', models.DateTimeField(null=True)),
                ('slurm_job_id', models.IntegerField(null=True)),
                ('verification_yaml_file_path', models.TextField(null=True)),
                ('job_data_dir', models.CharField(max_length=255)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('forecast_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.forecastrun')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('performance_metrics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.performancemetrics')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.status')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_run',
            },
        ),
    ]
