# Generated by Django 5.2.6 on 2025-09-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0029_forecastcycle_availability_lag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='failure_messages',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='forecastforcingdownloadrun',
            name='failure_messages',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='failure_messages',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='failure_messages',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='verificationrun',
            name='failure_messages',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
