# Generated by Django 5.2.6 on 2025-09-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0030_calibrationrun_failure_messages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastrun',
            name='forcing_download_run',
        ),
        migrations.DeleteModel(
            name='ForecastForcingDownloadRun',
        ),
    ]
