# Generated by Django 5.2.6 on 2025-09-24 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0031_remove_forecastrun_forcing_download_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationrun',
            name='failure_messages',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='forecastrun',
            name='cycle_date',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecastrun',
            name='failure_messages',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='failure_messages',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='verificationrun',
            name='failure_messages',
            field=models.TextField(null=True),
        ),
    ]
