# Generated by Django 5.2.6 on 2025-09-25 20:15
from django.db import migrations


def cleanup_forecastcycle(apps, schema_editor):
    """
    Clean up legacy ForecastCycle rows that would block the upcoming rename
    in 0034_rename_forecastcycle_to_forecastconfiguration.

    Specifically:
    - Remove the legacy 'Medium Range Forecast' variants that contain NULLs or
      inconsistent values, which will otherwise violate constraints once the
      table is renamed and fields are tightened in later migrations.
    """
    ForecastCycle = apps.get_model('calibration', 'ForecastCycle')

    # Delete known problematic internal_name variants
    ForecastCycle.objects.filter(
        internal_name__in=['medium_range', 'medium_range_forecast', 'medium_range_blend']
    ).delete()


class Migration(migrations.Migration):
    # Run in separate transactions to avoid ALTER TABLE conflicts later
    atomic = False

    dependencies = [
        ('calibration', '0033_update_forecast_cycles'),
    ]

    operations = [
        migrations.RunPython(cleanup_forecastcycle, reverse_code=migrations.RunPython.noop),
    ]
