# Generated by Django 5.2.6 on 2025-09-25 17:24

from django.db import migrations


def delete_medium_range_blend(apps, schema_editor):
    ForecastCycle = apps.get_model('calibration', 'ForecastCycle')
    ForecastCycle.objects.filter(internal_name='medium_range_blend').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0032_alter_calibrationrun_failure_messages_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_medium_range_blend, reverse_code=migrations.RunPython.noop),
    ]
