# Generated by Django 5.2.6 on 2025-09-30 21:25

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0035_adjust_forecast_configuration_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastrun',
            name='cold_start_date',
        ),
        migrations.AlterField(
            model_name='forecastrun',
            name='calibration_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts_from_calibration', to='calibration.calibrationrun'),
        ),
        migrations.CreateModel(
            name='ColdStartRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(null=True)),
                ('run_start', models.DateTimeField(null=True)),
                ('run_end', models.DateTimeField(null=True)),
                ('slurm_job_id', models.IntegerField(null=True)),
                ('failure_messages', models.TextField(null=True)),
                ('cold_start_date', models.DateTimeField(null=True)),
                ('calibration_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='calibration.calibrationrun')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.forecastconfiguration')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performance_metrics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.performancemetrics')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.status')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cold_start_run',
            },
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='cold_start_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts_from_cold_start', to='calibration.coldstartrun'),
        ),
    ]
