# Generated by Django 5.2.6 on 2025-10-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0036_remove_forecastrun_cold_start_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coldstartrun',
            index=models.Index(fields=['calibration_run'], name='idx_coldstart_calibration_run'),
        ),
        migrations.AddIndex(
            model_name='coldstartrun',
            index=models.Index(fields=['status'], name='idx_coldstart_status'),
        ),
        migrations.AddIndex(
            model_name='coldstartrun',
            index=models.Index(fields=['cold_start_date'], name='idx_coldstart_date'),
        ),
        migrations.AddIndex(
            model_name='forecastrun',
            index=models.Index(fields=['calibration_run'], name='idx_forecast_calibration_run'),
        ),
        migrations.AddIndex(
            model_name='forecastrun',
            index=models.Index(fields=['cold_start_run'], name='idx_forecast_cold_start_run'),
        ),
        migrations.AddIndex(
            model_name='forecastrun',
            index=models.Index(fields=['status'], name='idx_forecast_status'),
        ),
        migrations.AddIndex(
            model_name='forecastrun',
            index=models.Index(fields=['cycle_date'], name='idx_forecast_cycle_date'),
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['calibration_run'], name='idx_validation_calibration_run'),
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['status'], name='idx_validation_status'),
        ),
        migrations.AddIndex(
            model_name='verificationrun',
            index=models.Index(fields=['forecast_run'], name='idx_verif_forecast_run'),
        ),
        migrations.AddIndex(
            model_name='verificationrun',
            index=models.Index(fields=['owner'], name='idx_verif_owner'),
        ),
        migrations.AddIndex(
            model_name='verificationrun',
            index=models.Index(fields=['status'], name='idx_verif_status'),
        ),
    ]
