# Generated by Django 5.2.6 on 2025-10-07 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0037_coldstartrun_idx_coldstart_calibration_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldstartrun',
            name='cycle_date',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coldstartrun',
            name='cold_start_date',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
