# Generated by Django 5.2.7 on 2025-10-16 23:17

from django.db import migrations, models


def populate_display_name(apps, schema_editor):
    Module = apps.get_model('calibration', 'Module')
    for module in Module.objects.all():
        module.display_name = module.name
        module.save(update_fields=['display_name'])


class Migration(migrations.Migration):
    dependencies = [
        ('calibration', '0038_coldstartrun_cycle_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='description',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='objective_function',
        ),
        migrations.AddField(
            model_name='module',
            name='display_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RunPython(populate_display_name, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='module',
            name='display_name',
            field=models.CharField(max_length=50, unique=True, null=False),
        ),
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
