# Generated by Django 5.2.7 on 2025-10-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0039_rename_description_metric_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='objective_function',
            field=models.BooleanField(default=False),
        ),
    ]
