# Generated by Django 5.2.7 on 2025-10-20 14:42

from django.db import migrations


def rename_module(apps, schema_editor):
    Module = apps.get_model("calibration", "Module")
    obj = Module.objects.filter(name="Topoflow").first()
    if obj:
        obj.name = "Topoflow-Glacier"
        obj.save(update_fields=["name"])


class Migration(migrations.Migration):
    dependencies = [
        ('calibration', '0040_metric_objective_function'),
    ]

    operations = [
        migrations.RunPython(rename_module)
    ]
