# Generated by Django 5.2.7 on 2025-10-21 21:22

from django.db import migrations


def delete_forecast(apps, schema_editor):
    ForecastConfiguration = apps.get_model("calibration", "ForecastConfiguration")
    ForecastConfiguration.objects.filter(name="Long Range Forecast").delete()


class Migration(migrations.Migration):
    dependencies = [
        ('calibration', '0041_rename_topoflow'),
    ]

    operations = [
        migrations.RunPython(delete_forecast)
    ]
