# Generated by Django 5.2.7 on 2025-10-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0042_delete_long_range_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastconfiguration',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
