# Generated by Django 5.2.7 on 2025-10-22 13:27

from django.db import migrations


def delete_plot(apps, schema_editor):
    PlotDefinition = apps.get_model("calibration", "PlotDefinition")
    PlotDefinition.objects.filter(name="Forecast Hydrograph").delete()


class Migration(migrations.Migration):
    dependencies = [
        ('calibration', '0043_forecastconfiguration_order'),
    ]

    operations = [
        migrations.RunPython(delete_plot)
    ]
