# Generated by Django 5.2.7 on 2025-10-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0044_delete_forecast_hydrograph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationrun',
            old_name='verification_yaml_file_path',
            new_name='verification_config',
        ),
    ]
