# Generated by Django 5.2.7 on 2025-10-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0045_rename_verification_yaml_file_path_verificationrun_verification_config'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calibrationrun',
            index=models.Index(fields=['owner', 'is_archived', 'status', '-id'], name='idx_run_owner_arch_stat_id'),
        ),
        migrations.AddIndex(
            model_name='forecastrun',
            index=models.Index(fields=['calibration_run', 'status', '-id'], name='idx_fcst_run_status_id_desc'),
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['calibration_run', 'validation_type', '-id'], name='idx_val_run_type_id_desc'),
        ),
    ]
