# Generated by Django 5.2.7 on 2025-10-24 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0046_calibrationrun_idx_run_owner_arch_stat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrun',
            name='forecast_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.forecastrun'),
        ),
    ]
