# Generated by Django 5.2.7 on 2025-10-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0047_alter_verificationrun_forecast_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrun',
            name='job_data_dir',
        ),
    ]
