# Generated by Django 5.2.7 on 2025-10-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0048_remove_verificationrun_job_data_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrun',
            name='verification_config',
        ),
    ]
