# Generated by Django 5.2.7 on 2025-11-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0049_remove_verificationrun_verification_config'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='verificationrun',
            name='idx_verif_owner',
        ),
        migrations.RemoveField(
            model_name='verificationrun',
            name='owner',
        ),
        migrations.AddIndex(
            model_name='calibrationformulation',
            index=models.Index(fields=['module'], name='idx_formulation_module'),
        ),
        migrations.AddIndex(
            model_name='calibrationformulation',
            index=models.Index(fields=['calibration_run', 'module'], name='idx_formulation_run_module'),
        ),
    ]
