# Generated by Django 5.2.8 on 2025-11-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0050_remove_verificationrun_idx_verif_owner_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calibrationrun',
            index=models.Index(fields=['owner', 'is_archived', 'created_at'], name='idx_run_owner_arch_created'),
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['calibration_run', 'validation_type', 'status'], name='idx_val_run_type_status'),
        ),
    ]
