# Generated by Django 5.2.8 on 2025-11-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0051_calibrationrun_idx_run_owner_arch_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='sent_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coldstartrun',
            name='sent_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='sent_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='sent_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='verificationrun',
            name='sent_date',
            field=models.DateTimeField(null=True),
        ),
    ]
