# Generated by Django 5.2.8 on 2025-11-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0052_calibrationrun_sent_date_coldstartrun_sent_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='elapsed_time',
            new_name='run_time',
        ),
    ]
