# Generated by Django 5.2.8 on 2025-11-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0053_rename_elapsed_time_performancemetrics_run_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='archive_status_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
