# Generated by Django 5.2.9 on 2025-12-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0053_rename_elapsed_time_performancemetrics_run_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='node_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='num_catchments',
            field=models.IntegerField(null=True),
        ),
    ]
