# Generated by Django 5.2.10 on 2026-01-09 19:34

from django.db import migrations
from django.db.models import Q


def delete_user_upload(apps, schema_editor):
    db = schema_editor.connection.alias

    CalibrationRun = apps.get_model("calibration", "CalibrationRun")
    ForcingSource = apps.get_model("calibration", "ForcingSource")
    ObservationalSource = apps.get_model("calibration", "ObservationalSource")
    GeopackageSource = apps.get_model("calibration", "GeopackageSource")

    fs_ids = list(ForcingSource.objects.using(db).filter(name="User Upload").values_list("id", flat=True))
    os_ids = list(ObservationalSource.objects.using(db).filter(name="User Upload").values_list("id", flat=True))
    gs_ids = list(GeopackageSource.objects.using(db).filter(name="User Upload").values_list("id", flat=True))

    q = Q()
    if fs_ids:
        q |= Q(forcing_source_requested_id__in=fs_ids) | Q(forcing_source_actual_id__in=fs_ids)
    if os_ids:
        q |= Q(observational_source_id__in=os_ids)
    if gs_ids:
        q |= Q(geopackage_source_id__in=gs_ids)

    # Delete the runs
    if q:
        CalibrationRun.objects.using(db).filter(q).delete()

    # Now delete the source rows
    ForcingSource.objects.using(db).filter(id__in=fs_ids).delete()
    ObservationalSource.objects.using(db).filter(id__in=os_ids).delete()
    GeopackageSource.objects.using(db).filter(id__in=gs_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('calibration', '0055_calibrationrun_node_type_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_user_upload, reverse_code=migrations.RunPython.noop),
    ]
