# Generated by Django 5.2.10 on 2026-01-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0056_delete_user_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gage',
            name='altitude_accuracy',
        ),
        migrations.RemoveField(
            model_name='gage',
            name='altitude_datum',
        ),
        migrations.RemoveField(
            model_name='gage',
            name='lat_long_accuracy',
        ),
        migrations.RemoveField(
            model_name='gage',
            name='lat_long_datum',
        ),
        migrations.RemoveField(
            model_name='gage',
            name='site_type',
        ),
    ]
