# Generated by Django 5.2.10 on 2026-01-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0057_remove_gage_altitude_accuracy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastconfiguration',
            name='fcst_timestep',
        ),
        migrations.RemoveField(
            model_name='forecastconfiguration',
            name='time_range',
        ),
    ]
