# Generated by Django 5.2.10 on 2026-01-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0058_remove_forecastconfiguration_fcst_timestep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastconfiguration',
            name='fcst_timestep',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
