# Generated by Django 5.2.10 on 2026-02-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0059_forecastconfiguration_fcst_timestep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='user_formulation_name',
            new_name='job_name',
        ),
    ]
