# Generated by Django 5.2.11 on 2026-02-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0060_rename_user_formulation_name_calibrationrun_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='display_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
