# Generated by Django 5.2.11 on 2026-02-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0061_domain_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationrun',
            name='geopackage_eds_file_path',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='observational_eds_file_path',
        ),
    ]
