# Generated by Django 5.2.11 on 2026-02-26 15:39

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0062_remove_calibrationrun_geopackage_eds_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='use_edfs',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ModuleProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('data_type', models.CharField(max_length=50)),
                ('default_value', models.CharField(max_length=200)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='properties', to='calibration.module')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'module_property',
            },
        ),
        migrations.CreateModel(
            name='CalibrationModulePropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value_bool', models.BooleanField(null=True)),
                ('value_int', models.IntegerField(null=True)),
                ('value_double', models.FloatField(null=True)),
                ('value_str', models.CharField(max_length=500, null=True)),
                ('calibration_formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_property_values', to='calibration.calibrationformulation')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module_property', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='calibration.moduleproperty')),
            ],
            options={
                'db_table': 'calibration_module_property_value',
            },
        ),
        migrations.CreateModel(
            name='ModulePropertyChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=120)),
                ('value_int', models.IntegerField(null=True)),
                ('value_str', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='calibration.moduleproperty')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'module_property_choice',
            },
        ),
        migrations.AddConstraint(
            model_name='moduleproperty',
            constraint=models.UniqueConstraint(fields=('module', 'name'), name='uq_module_property__module_name'),
        ),
        migrations.AddIndex(
            model_name='calibrationmodulepropertyvalue',
            index=models.Index(fields=['calibration_formulation'], name='idx_cal_mod_prop_val_form'),
        ),
        migrations.AddIndex(
            model_name='calibrationmodulepropertyvalue',
            index=models.Index(fields=['module_property'], name='idx_cal_mod_prop_val_property'),
        ),
        migrations.AddConstraint(
            model_name='calibrationmodulepropertyvalue',
            constraint=models.UniqueConstraint(fields=('calibration_formulation', 'module_property'), name='uq_calibration_module_property_value__formulation_property'),
        ),
        migrations.AddConstraint(
            model_name='calibrationmodulepropertyvalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value_bool__isnull', False), ('value_int__isnull', True), ('value_double__isnull', True), ('value_str__isnull', True)), models.Q(('value_bool__isnull', True), ('value_int__isnull', False), ('value_double__isnull', True), ('value_str__isnull', True)), models.Q(('value_bool__isnull', True), ('value_int__isnull', True), ('value_double__isnull', False), ('value_str__isnull', True)), models.Q(('value_bool__isnull', True), ('value_int__isnull', True), ('value_double__isnull', True), ('value_str__isnull', False)), _connector='OR'), name='ck_calibration_module_property_value_exactly_one'),
        ),
        migrations.AddIndex(
            model_name='modulepropertychoice',
            index=models.Index(fields=['module_property', 'sort_order'], name='module_prop_module__35797a_idx'),
        ),
        migrations.AddConstraint(
            model_name='modulepropertychoice',
            constraint=models.UniqueConstraint(condition=models.Q(('value_int__isnull', False)), fields=('module_property', 'value_int'), name='uq_property_choice__prop_value_int'),
        ),
        migrations.AddConstraint(
            model_name='modulepropertychoice',
            constraint=models.UniqueConstraint(condition=models.Q(('value_str__isnull', False)), fields=('module_property', 'value_str'), name='uq_property_choice__prop_value_str'),
        ),
        migrations.AddConstraint(
            model_name='modulepropertychoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value_int__isnull', False), ('value_str__isnull', True)), models.Q(('value_int__isnull', True), ('value_str__isnull', False)), _connector='OR'), name='ck_choice_exactly_one_value'),
        ),
    ]
