# Generated by Django 5.2.11 on 2026-02-25 18:35

from django.db import migrations


MODULE_NAMES = ("CFE-S", "CFE-X")
PROP_NAME = "aet_rootzone"
DISPLAY_NAME = "AET Rootzone"
DESCRIPTION = "Enable rootzone option."
DATA_TYPE = "boolean"
DEFAULT_VALUE = "false"


def forwards(apps, schema_editor):
    Module = apps.get_model("calibration", "Module")
    CalibrationRun = apps.get_model("calibration", "CalibrationRun")
    CalibrationFormulation = apps.get_model("calibration", "CalibrationFormulation")
    ModuleProperty = apps.get_model("calibration", "ModuleProperty")
    CalibrationModulePropertyValue = apps.get_model("calibration", "CalibrationModulePropertyValue")

    # If no runs exist (fresh install), nothing to do.
    if not CalibrationRun.objects.exists():
        return

    # Only runs that used the legacy flag need migration.
    runs = CalibrationRun.objects.filter(is_aet_rootzone=True).only("id")
    if not runs.exists():
        return

    # Resolve the target modules. If they don't exist in this environment, no-op.
    modules = list(Module.objects.filter(name__in=MODULE_NAMES).only("id", "name"))
    if not modules:
        return

    module_by_name = {m.name: m for m in modules}

    # Ensure ModuleProperty exists for each module (idempotent).
    # Explicitly set created_by/updated_by to None to avoid django_currentuser default behavior in migrations.
    prop_by_module_id: dict[int, object] = {}
    for module_name in MODULE_NAMES:
        m = module_by_name.get(module_name)
        if not m:
            continue

        prop, created = ModuleProperty.objects.get_or_create(
            module_id=m.id,
            name=PROP_NAME,
            defaults={
                "display_name": DISPLAY_NAME,
                "description": DESCRIPTION,
                "data_type": DATA_TYPE,
                "default_value": DEFAULT_VALUE,
                "created_by": None,
                "updated_by": None,
            },
        )

        # Safety: ensure display_name is correct if property already existed
        if not created and prop.display_name != DISPLAY_NAME:
            prop.display_name = DISPLAY_NAME
            prop.updated_by = None
            prop.save(update_fields=["display_name", "updated_by"])

        prop_by_module_id[m.id] = prop

    if not prop_by_module_id:
        return

    target_module_ids = list(prop_by_module_id.keys())

    # For each run with is_aet_rootzone=True, set the module property value_bool=True on the run's target formulations.
    for run in runs.iterator():
        formulations = CalibrationFormulation.objects.filter(
            calibration_run_id=run.id,
            module_id__in=target_module_ids,
        ).only("id", "module_id")

        for f in formulations:
            prop = prop_by_module_id.get(f.module_id)
            if not prop:
                continue

            # Idempotent: respects unique constraint (formulation, module_property).
            CalibrationModulePropertyValue.objects.get_or_create(
                calibration_formulation_id=f.id,
                module_property_id=prop.id,
                defaults={
                    "value_bool": True,
                    "value_int": None,
                    "value_double": None,
                    "value_str": None,
                    "created_by": None,
                    "updated_by": None,
                },
            )


def backwards(apps, schema_editor):
    # Optional: delete only the rows this migration likely created.
    Module = apps.get_model("calibration", "Module")
    ModuleProperty = apps.get_model("calibration", "ModuleProperty")
    CalibrationModulePropertyValue = apps.get_model("calibration", "CalibrationModulePropertyValue")

    module_ids = list(Module.objects.filter(name__in=MODULE_NAMES).values_list("id", flat=True))
    if not module_ids:
        return

    prop_ids = list(
        ModuleProperty.objects.filter(module_id__in=module_ids, name=PROP_NAME).values_list("id", flat=True)
    )
    if not prop_ids:
        return

    # Conservative rollback: remove only rows that are True for this property.
    CalibrationModulePropertyValue.objects.filter(
        module_property_id__in=prop_ids,
        value_bool=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0063_module_use_edfs_moduleproperty_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
