# Generated by Django 5.2.11 on 2026-03-04 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0064_migrate_aet_rootzone_to_module_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationrun',
            name='is_aet_rootzone',
        ),
    ]
