# Generated by Django 5.2.12 on 2026-03-19 00:11

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0065_remove_calibrationrun_is_aet_rootzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastconfiguration',
            name='supports_hindcast',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HindcastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(null=True)),
                ('sent_date', models.DateTimeField(null=True)),
                ('run_start', models.DateTimeField(null=True)),
                ('run_end', models.DateTimeField(null=True)),
                ('slurm_job_id', models.IntegerField(null=True)),
                ('failure_messages', models.TextField(null=True)),
                ('interval_cycle', models.IntegerField()),
                ('num_iterations', models.IntegerField()),
                ('cycle_date', models.DateTimeField()),
                ('calibration_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hindcasts_from_calibration', to='calibration.calibrationrun')),
                ('cold_start_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hindcasts_from_cold_start', to='calibration.coldstartrun')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.forecastconfiguration')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performance_metrics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.performancemetrics')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.status')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hindcast_run',
                'indexes': [models.Index(fields=['calibration_run'], name='idx_hindcast_calibration_run'), models.Index(fields=['cold_start_run'], name='idx_hindcast_cold_start_run'), models.Index(fields=['status'], name='idx_hindcast_status'), models.Index(fields=['cycle_date'], name='idx_hindcast_cycle_date'), models.Index(fields=['calibration_run', 'status', '-id'], name='idx_hcst_run_status_id_desc')],
            },
        ),
    ]
