# Generated by Django 5.2.13 on 2026-04-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0068_hindcastrun_created_new_cold_start'),
        ('calibration', '0068_mfarecoverycode'),
    ]

    operations = [
    ]
