# Generated by Django 5.2.13 on 2026-05-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0069_merge_20260428_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationrun',
            name='forcing_eds_dir_path',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='forcing_source_actual',
        ),
        migrations.AddField(
            model_name='forcingsource',
            name='display_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metric',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
    ]
