# Generated by Django 5.2.13 on 2026-05-04 18:44

from django.db import migrations


def rename_nwm_retrospective(apps, schema_editor):
    ForcingSource = apps.get_model("calibration", "ForcingSource")

    ForcingSource.objects.filter(name="NWM Retrospective").update(
        name="NWM"
    )


def reverse_rename_nwm_retrospective(apps, schema_editor):
    ForcingSource = apps.get_model("calibration", "ForcingSource")

    ForcingSource.objects.filter(name="NWM").update(
        name="NWM Retrospective"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0069_remove_calibrationrun_forcing_eds_dir_path_and_more'),
    ]

    operations = [
        migrations.RunPython(
            rename_nwm_retrospective,
            reverse_rename_nwm_retrospective,
        ),
    ]
