# Generated by Django 5.2.13 on 2026-05-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0070_rename_nwm_retrospective'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='forcing_source_requested',
            new_name='forcing_source',
        ),
    ]
